### ISSUE TITLE
Add packages use in the notebook to the image

### ISSUE THREAD

**Issue by bsipocz** [fornax-navo/fornax-demo-notebooks#30] opened 2022-08-10 02:18 UTC
We should be able to clear out package installations from the notebook(s). 

For the forced photometry notebook these are the ones:

 - pandas
 - seaborn
 - mpld3
 - boto3
 - nway

(and these packages are already been assumed to be available: astropy, astroquery, scikit-image, numpy, matplotlib, tractor, firefly)

**Comment by bsipocz** [comment] 2022-08-15 19:58
cc @trjaffe

**Comment by jkrick** [comment] 2023-09-13 16:21
I think it is fine, or even valuable, to have package installs in the notebook for potentially two reasons:

1. serves as an example for users to see how they might install packages they need.  
2. Is there a speed difference to having package installs in the image vs. in the notebook?  Sometimes the SMCE takes a long time to start up, and I wonder if some of that slowdown is caused by package installs.  In that case, I would rather they go in the notebooks than in the image.

@bsipocz @stargaser  what are your opinions on this?

**Comment by trjaffe** [comment] 2023-09-13 17:55
@zoghbi-a can comment better, but it's unlikely that python installs are slowing down the initial launch of the container.  In the high energy case, the software build is indeed huge (of order 10GB), so it does, but that's a separate case AFAIK.

**Comment by bsipocz** [comment] 2023-09-13 18:03
I think we need to ship the minimum requirements with the image. E.g. all the libraries that are needed to access the data, do the basic plots etc. So basically everything works out of the box.
Having everything in the image also provides us the control and knowledge that the versions are cross compatible and the notebook works as expected.


But I also see the value in your point 1); so we could leave the extra for the that. E.g. we have matplotlib in the image, but show how to install seaborn?

**Comment by bsipocz** [comment] 2023-09-13 18:04
(we also cannot really expect the users to install things like tractor, after all having it pre-installed is one of the reasons they come to the platform)

**Comment by zoghbi-a** [comment] 2023-09-13 18:23
> @zoghbi-a can comment better, but it's unlikely that python installs are slowing down the initial launch of the container. In the high energy case, the software build is indeed huge (of order 10GB), so it does, but that's a separate case AFAIK.

Yes. The slow start is likely because of the time it takes to setup and launch a compute instance. You can see that in the same image. Sometimes it starts quickly, and sometimes it takes time. That is at the AWS side.

I would agree that the image should contain most useful software pre-installed. The infrastructure code is not yet at the stage where we can easily modify the image to install what we want. Once we have that setup, my suggestion has been to make a base image with basic useful software, and then other images can build on it to add other software (e.g. tractor, heasoft etc.)

**Comment by trjaffe** [comment] 2023-09-13 18:35
Do we need to submit an issue on Fornaxdev that the startup is too slow?  I believe the current strategy is to start with the cheapest options and add as needed.  For instance, I thought they already did step this up one $$ step to make the startup faster.  Either that fell off somehow or is insufficient and we maybe need another step.  (This is to do with reserving, and therefore paying for, instances that are always running I believe.)

**Comment by zoghbi-a** [comment] 2023-09-13 18:41
I think it will be great if we can do some profiling so we know what to expect and so it is documented.

**Comment by stargaser** [comment] 2023-09-13 18:51
I think the image should have most useful software pre-installed. I don't think it affects the startup. Tractor is too difficult for a user installation and I think we should provide an image with it, with a non-Tractor image as another option with more up-to-date software. I've also found that installing an upgraded pyarrow in a notebook can fail so that's another reason to pre-install packages.

It's probably a good idea to submit a separate issue about the startup times.

**Comment by jkrick** [comment] 2023-09-13 20:51
ok, assuming the number of packages has no effect on speed to startup, then of course we all agree the "useful" ones should be pre-installed, but what is that list?

The light curve notebook pip installs the following list:
acstools
astropy
astroquery
git+https://github.com/fkiwy/unTimely_Catalog_explorer
hpgeom
lightkurve
matplotlib
numpy
pandas
pyvo
reproject  # needed for untimely
s3fs
tqdm
wget

The forced photometry notebook pip installs the following list:
numpy
matplotlib
scikit-image
pandas
seaborn
statsmodels
mpld3
firefly_client
astropy
astroquery
nway
boto3
tqdm


I would think 'most useful' to be pre-installed in the image would contain:
numpy 
matplotlib
pandas
astropy
astroquery
tqdm
pyvo


ps, new issue opened to benchmark the startup times, issue #142

**Comment by troyraen** [comment] 2023-09-14 00:13
I'm guessing that both `s3fs` and `boto3` will be in the "most useful" category as well.

**Comment by stargaser** [comment] 2023-09-14 18:15
For working with Parquet catalogs, I would add
pyarrow
hpgeom

Some interactive image display packages require extensions to Jupyterlab, which might not be doable as a user and would therefore need to be pre-installed:
ipyaladin
jupyter_firefly_extensions (requires firefly_client and some environment variables)

**Comment by stargaser** [comment] 2023-11-01 23:57
Abdu made a new "tractor" image in Gitlab in the fornax-images repo. I've made some updates in https://git.smce.nasa.gov/fornax/fornax-images/-/merge_requests/12.

Let's keep this issue open until the new image is deployed and tested.

**Comment by stargaser** [comment] 2023-11-21 16:40
The packages are available on the Fornaxdev SMCE as "Tractor Test Image (Do Not Use)". The forced photometry notebook runs successfully.

Closing this issue.

**Closed by stargaser** 2023-11-21 16:40 UTC
Labels: infrastructure
